# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to FTP 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, test
        run: |
          npm install
          npm test

  deploy:
    name: Deploy 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: 4.172.209.98
          user: user
          password: user
